# Generated by Django 3.2 on 2023-04-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipologia_cliente', models.CharField(choices=[('ND', 'Non Definita'), ('CD', 'Condominio'), ('PS', 'Persona'), ('AZ', 'Azienda')], default='ND', max_length=2)),
                ('aoo', models.IntegerField(default=0)),
                ('denominazione', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ragione_sociale', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cognome', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventi.fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descrizione', models.CharField(max_length=200)),
                ('minuti_intervento', models.IntegerField(default=0)),
                ('quantita_operatori', models.IntegerField(default=1)),
                ('importo_operatore', models.IntegerField(default=25)),
                ('iva_operatore', models.IntegerField(default=22)),
                ('quantita_materiale', models.IntegerField(default=0)),
                ('importo_materiale', models.IntegerField(default=0)),
                ('iva_materiale', models.IntegerField(default=22)),
                ('importo_chiamata', models.IntegerField(default=25)),
                ('iva_chiamata', models.IntegerField(default=22)),
                ('tipologia_cliente', models.CharField(choices=[('NF', 'Non Fatturabile'), ('DF', 'Da Fatturare'), ('FT', 'Fatturato')], default='DF', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventi.cliente')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interventi.operatore')),
            ],
        ),
    ]
