# Generated by Django 3.2 on 2023-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cognome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='denominazione',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
