# Generated by Django 3.2 on 2023-04-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0003_auto_20230421_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervento',
            old_name='tipologia_cliente',
            new_name='fattura',
        ),
    ]
