# Generated by Django 3.2 on 2023-04-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventi', '0004_rename_tipologia_cliente_intervento_fattura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervento',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
